### ISSUE TITLE
Links and buttons are still purple in certain places even with purpilized off

### ISSUE THREAD

**Issue by hazygonuttz** [gliczide/Rescratcher#1]
Apologies if this issue isn't written super well, I haven't touched Github for a long time now.

Areas like the main page footer and the follow/post comment buttons on profile pages still use purple, even when I turn the purpilized setting off.

<img width="1066" alt="Screenshot 2024-01-07 at 11 38 58 AM" src="https://github.com/gliczide/Rescratcher/assets/104270788/3e2aca25-cd70-4284-9e82-cc5f3055af26">

<img width="677" alt="Screenshot 2024-01-07 at 11 39 12 AM" src="https://github.com/gliczide/Rescratcher/assets/104270788/4ae78a53-3120-446e-8172-432848a014ae">

<img width="135" alt="Screenshot 2024-01-07 at 11 39 19 AM" src="https://github.com/gliczide/Rescratcher/assets/104270788/691c3b83-1694-456d-b96a-84237e55ed7b">

Edit: The explore page has the same issue as well

<img width="1024" alt="Screenshot 2024-01-07 at 11 42 28 AM" src="https://github.com/gliczide/Rescratcher/assets/104270788/b43f6b1f-6b17-4b2f-a79b-8c977785b0dd">

**Comment by gliczide** [comment]
Fixed in 1.0.2 version.
